name: Compilar APK CashTally Flutter Oficial

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código fuente
        uses: actions/checkout@v4

      - name: Configurar Java 17 (Requerido para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter Estable
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Dependencias del Proyecto
        run: |
          flutter pub get
          flutter clean
          flutter pub get

      - name: Compilar APK (Instalador Android)
        run: flutter build apk --split-per-abi

      - name: Subir Instalador Resultante
        uses: actions/upload-artifact@v4
        with:
          name: CashTally-APK-Final
          path: build/app/outputs/flutter-apk/*.apk
          
